### ISSUE TITLE
 Availability of Pretrained Weights for Chinese Users

### ISSUE THREAD

**Issue by euminds** [sdc17/UPop#24]
Hi,

Can you update a version of the pretrained weights that can be shared through popular cloud storage platforms such as Baidu Netdisk or OneDrive, which are widely used in China.  some of users in mainland China have reported difficulties in accessing the pretrained weights due to the need for a proxy or VPN connection to bypass internet censorship.

Best

**Comment by sdc17** [comment]
Thanks for this reminder. We will upload them to more accessible cloud storage in mainland China. It may take a few days, and we will ping you once it's done.

**Comment by sdc17** [comment]
Hi, we have uploaded them to Baidu Netdisk. Please check our updated readme :)
