### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by HaoFYu** [sdc17/UPop#32]
是否可以提供VQA v2和visual genome数据集的网盘文件，文中所提供的链接现在无法打开或下载

**Comment by sdc17** [comment]
您好，这个可能涉及版权问题，我们无法直接提供网盘下载。
如果提供的链接下载不了的话，可以在HuggingFace，Kaggle，或者国内的Opendatalab这些网站上搜索这些数据集，应该都可以下载到的。
